### ISSUE TITLE
IP's are added to csf.deny regardless of ip range *.*.*.0/24"

### ISSUE THREAD

**Issue by Logic-7E8** [ShaneOss/AbuseIPDB-cPanel-CSF#1]
If I add an IP range for example "*.*.*.0/24", to block an entire range from 1 to 254, the abusechecker still adds IP's from that range to csf.deny regardless of the overlapping deny rule: *.*.*.0/24

**Comment by ShaneOss** [comment]
Hey @Logic-7E8 ,
Try the attached and let me know how it goes for you. If all good, I'll push the update to the code. Thanks!
[checkipabuseipdb.sh.txt](https://github.com/user-attachments/files/17274304/checkipabuseipdb.sh.txt)

**Comment by Logic-7E8** [comment]
@ShaneOss 

Thank you for your quick reply,

I have tried your suggestion, however the iterations seem to have become very slow compared to previous script, besides that the script still adds IP's to the deny list.

Load seems to increase significantly too.

![image](https://github.com/user-attachments/assets/7a2ebca4-76f9-4a6b-9b46-cb318a545f57)

**Comment by ShaneOss** [comment]
Try this one, It uses grepcidr. Should be more efficient.
sudo apt-get install grepcidr
[checkipabuseipdb.sh.txt](https://github.com/user-attachments/files/17285830/checkipabuseipdb.sh.txt)

**Comment by Logic-7E8** [comment]
> Try this one, It uses grepcidr. Should be more efficient. sudo apt-get install grepcidr [checkipabuseipdb.sh.txt](https://github.com/user-attachments/files/17285830/checkipabuseipdb.sh.txt)

Thank again!, is this script working for you because for me it took about 3,5 hours to check the error_log against 3500 IP's to and a few ranges, still failed to find IP that matches a certain blocked range.

**Comment by ShaneOss** [comment]
All good. I wrote the original script a while ago. I haven't used WHM and CSF for about the last year and a half. Moved into the Azure space. Although I get what you want to do and there's always room for improvement. But I can't test it these days.

_"still failed to find IP that matches a certain blocked range."_
Essentially this is what you want right? If there's a range already defined and the IP to be blocked as it's shown up, already exists within a pre defined range then don't add it again?
The last test script was resource intensive because of the way it looked up the IP against the CIDR using regex. Using grepcidr is a compiled application and should.. be more efficient. Thought about using ipcalc.

You can test grepcidr locally e.g. echo "192.168.0.15" | grepcidr "192.168.0.0/24"

If using x's in your blocked cidr range it won't work with the grepcidr check. e.g. 2x.7x.214.0/23

**Comment by Logic-7E8** [comment]
> _All good. I wrote the original script a while ago. I haven't used WHM and CSF for about the last year and a half. Moved into the Azure space. Although I get what you want to do and there's always room for improvement. But I can't test it these days._

No worries, in fact I was surprised I even got a reply seeing it's a 4 year old repo. ;-)

> _"still failed to find IP that matches a certain blocked range."
> Essentially this is what you want right? If there's a range already defined and the IP to be blocked as it's shown up, already exists within a pre defined range then don't add it again?_

Correct!

> _You can test grepcidr locally e.g. echo "192.168.0.15" | grepcidr "192.168.0.0/24"_

The command `echo "192.168.0.15" | grepcidr "192.168.0.0/24"` returns a result, were `echo "192.168.1.15" | grepcidr "192.168.0.0/24"` does not, so that seems to be working.

> _If using x's in your blocked cidr range it won't work with the grepcidr check. e.g. 2x.7x.214.0/23_

For now I have only added CIDR range in this format to csf.deny `192.168.0.0/24`

**Comment by Logic-7E8** [comment]
Right, I managed to get it working, see attached file.

Seems the problem was in the first `if ` statement in `# Process IP addresses`, after changing `if csf -g "$ip" > /dev/null 2>&1; then` to `if grep -q "$ip" "$csf_deny"; then` it started working (and just as fast as the original script)

Although the script is adding a white space to each new line in `csf.deny`, (not quite sure where that comes from tho) it seems to work fine regardless.

![CIDR](https://github.com/user-attachments/assets/0b03a39b-40dd-4a99-9f09-4dc86fb27c17)

See revised file:

[CIDR check.txt](https://github.com/user-attachments/files/17293675/CIDR.check.txt)

**Comment by ShaneOss** [comment]
This should fix the whitepace issue too caused by multiline print statement.
[checkipabuseipdb.sh.txt](https://github.com/user-attachments/files/17299967/checkipabuseipdb.sh.txt)

**Comment by Logic-7E8** [comment]
> This should fix the whitepace issue too caused by multiline print statement. [checkipabuseipdb.sh.txt](https://github.com/user-attachments/files/17299967/checkipabuseipdb.sh.txt)

Cool!, that wraps it up, thanks for the script and help, closing this as completed.
